### ISSUE TITLE
ImportError while importing test module

### ISSUE THREAD

**Issue by vu-truong** [aimacode/aima-python#1173]
I followed the installation guide and after runing py.test I got this error:

```
======================================================= ERRORS ========================================================
___________________________________ ERROR collecting tests/test_deep_learning4e.py ____________________________________
ImportError while importing test module 'C:\Works\Aima\aima-python\tests\test_deep_learning4e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py:58: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:28: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:24: in swig_import_helper
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py:242: in load_module
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py:342: in load_dynamic
    ???
E   ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:
tests\test_deep_learning4e.py:2: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\__init__.py:3: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\utils\__init__.py:6: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\utils\conv_utils.py:9: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\__init__.py:1: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\load_backend.py:90: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:5: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:101: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py:40: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:50: in __getattr__
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:44: in _load
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py:49: in <module>
    from tensorflow.python import pywrap_tensorflow
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py:74: in <module>
    ???
E   ImportError: Traceback (most recent call last):
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
E       from tensorflow.python.pywrap_tensorflow_internal import *
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
E       _pywrap_tensorflow_internal = swig_import_helper()
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
E       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
E       return load_dynamic(name, filename, file)
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
E       return _load(spec)
E   ImportError: DLL load failed: The specified module could not be found.
E
E
E   Failed to load the native TensorFlow runtime.
E
E   See https://www.tensorflow.org/install/errors
E
E   for some common reasons and solutions.  Include the entire stack trace
E   above this error message when asking for help.
--------------------------------------------------- Captured stderr ---------------------------------------------------
Using TensorFlow backend.
______________________________________ ERROR collecting tests/test_learning4e.py ______________________________________
ImportError while importing test module 'C:\Works\Aima\aima-python\tests\test_learning4e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py:58: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:28: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:24: in swig_import_helper
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py:242: in load_module
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py:342: in load_dynamic
    ???
E   ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:
tests\test_learning4e.py:3: in <module>
    ???
deep_learning4e.py:7: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\__init__.py:3: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\utils\__init__.py:6: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\utils\conv_utils.py:9: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\__init__.py:1: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\load_backend.py:90: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:6: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\eager\context.py:29: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:50: in __getattr__
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:44: in _load
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py:42: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\_api\v2\audio\__init__.py:10: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\ops\gen_audio_ops.py:9: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:50: in __getattr__
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:44: in _load
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py:49: in <module>
    from tensorflow.python import pywrap_tensorflow
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py:74: in <module>
    ???
E   ImportError: Traceback (most recent call last):
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
E       from tensorflow.python.pywrap_tensorflow_internal import *
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
E       _pywrap_tensorflow_internal = swig_import_helper()
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
E       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
E       return load_dynamic(name, filename, file)
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
E       return _load(spec)
E   ImportError: DLL load failed: The specified module could not be found.
E
E
E   Failed to load the native TensorFlow runtime.
E
E   See https://www.tensorflow.org/install/errors
E
E   for some common reasons and solutions.  Include the entire stack trace
E   above this error message when asking for help.
--------------------------------------------------- Captured stderr ---------------------------------------------------
Using TensorFlow backend.
_____________________________________ ERROR collecting tests/test_perception4e.py _____________________________________
ImportError while importing test module 'C:\Works\Aima\aima-python\tests\test_perception4e.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py:58: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:28: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py:24: in swig_import_helper
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py:242: in load_module
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py:342: in load_dynamic
    ???
E   ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:
tests\test_perception4e.py:5: in <module>
    ???
perception4e.py:4: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\__init__.py:3: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\utils\__init__.py:6: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\utils\conv_utils.py:9: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\__init__.py:1: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\load_backend.py:90: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\keras\backend\tensorflow_backend.py:6: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\eager\context.py:29: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:50: in __getattr__
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:44: in _load
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py:42: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\_api\v2\audio\__init__.py:10: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\ops\gen_audio_ops.py:9: in <module>
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:50: in __getattr__
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py:44: in _load
    ???
c:\users\vutruong\appdata\local\programs\python\python37\lib\importlib\__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py:49: in <module>
    from tensorflow.python import pywrap_tensorflow
c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py:74: in <module>
    ???
E   ImportError: Traceback (most recent call last):
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
E       from tensorflow.python.pywrap_tensorflow_internal import *
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
E       _pywrap_tensorflow_internal = swig_import_helper()
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
E       _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
E       return load_dynamic(name, filename, file)
E     File "c:\users\vutruong\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
E       return _load(spec)
E   ImportError: DLL load failed: The specified module could not be found.
E
E
E   Failed to load the native TensorFlow runtime.
E
E   See https://www.tensorflow.org/install/errors
E
E   for some common reasons and solutions.  Include the entire stack trace
E   above this error message when asking for help.
--------------------------------------------------- Captured stderr ---------------------------------------------------
Using TensorFlow backend.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 3 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================== 3 errors in 3.89s ==================================================
```

**Comment by HimanchalChandra** [comment]
If your CPU didn't support AVX instructions, you will get ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. (Win 10) or ImportError: DLL load failed with error code -1073741795 (Win 7) when using TensorFlow official release 1.6.0 and up (pip install TensorFlow). You can use pip install [filename].whl which file download from sse2 folder instead of using official AVX binary.

You can download the wheel file from here - [](https://pypi.org/project/tensorflow/1.14.0/#files)
I personally use Python 3.6.6 and Tensorflow 1.14.0 and the codebase works fine.

**Comment by HimanchalChandra** [comment]
If your CPU didn't support AVX instructions, you will get ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. (Win 10) or ImportError: DLL load failed with error code -1073741795 (Win 7) when using TensorFlow official release 1.6.0 and up (pip install TensorFlow). You can use pip install [filename].whl which file download from sse2 folder instead of using official AVX binary.

You can download the wheel file from here - [https://pypi.org/project/tensorflow/1.14.0/#files](url)
I use Python 3.6.6 and Tensorflow 1.14.0 and the codebase works fine.

**Comment by vu-truong** [comment]
I fixed it by installing Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019 [https://support.microsoft.com/vi-vn/help/2977003/the-latest-supported-visual-c-downloads](url).
I'm using Tensorflow 2.1.0
