### ISSUE TITLE
problem when I define my own problem in planning module

### ISSUE THREAD

**Issue by matgreco** [aimacode/aima-python#1193]
Hi,

I have been tryed to declare and solve my own planning problem using the graphplan algorithm. When I executed the graphplan algorithm i get the follow error:

```
Traceback (most recent call last):
  File "/home/mat/Doctorado/PDDL-Dataset/aima-python/PLANIFICADOR.py", line 102, in <module>
    solution = GraphPlan(shoppingProblem).execute()
  File "/home/mat/Doctorado/PDDL-Dataset/aima-python/planning.py", line 1004, in execute
    solution = self.extract_solution(self.graph.planning_problem.goals, -1)
  File "/home/mat/Doctorado/PDDL-Dataset/aima-python/planning.py", line 948, in extract_solution
    actions.append(level.next_state_links[goal])
KeyError: on(A, B)
```
The problem definition is this:
```python
def Blockworld_test():
    return PlanningProblem( initial = 'handempty & ontable(A) & ontable(B) & clear(A) & clear(B)',
                            goals =  'on(A, B)',
                            actions = [Action('Pick_Up(x)',
                                                precond='clear(x) & ontable(x) & handempty',
                                                effect='~clear(x) & ~ontable(x) & ~handempty & holding(x)',
                                                domain='Block(x)'),
                                        Action('Put_Down(x)',
                                                precond='holding(x)',
                                                effect='~holding(x) & clear(x) & handempty & ontable(x)',
                                                domain='Block(x)'),
                                        Action('Stack(x, y)',
                                                precond='holding(x) & clear(y)',
                                                effect='~holding(x) & ~clear(y) & clear(x) & handempty & on(x, y)',
                                                domain='Block(x) & Block(y)'),
                                        Action('Unstack(x, y)',
                                                precond='on(x,y) & clear(x) & handempty',
                                                effect='holding(x) & clear(y) & ~clear(x) & ~handempty & ~on(x, y)',
                                                domain='Block(x) & Block(y)')],
                            domain = 'Block(A) & Block(B)') 

shoppingProblem = Blockworld_test()
solution = GraphPlan(shoppingProblem).execute()
print(linearize(solution))
```
Also, I had been tryed to define another problem (gripper) and get a similar error.

```python
def gripper():
	return PlanningProblem(initial='at_robby(A) & free(left) & free(right) & at(W, A) & at(X, A) & at(Y, A) & at(Z, A)',
                           goals='at(W, B) & at(X, B) & at(Y, B) & at(Z, B)' ,
                           actions=[Action('Move(f, t)',
                           				precond='at_robby(f)',
                           				effect ='at_robby(t) & ~at_robby(f)',
                           				domain ='Room(f) & Room(t)'
                           				),
                           			Action('Pick(obj, R, gripper)',
                           				precond='at(obj, R) & at_robby(R) & free(gripper)',
                           				effect ='carry(obj, gripper) & ~at(obj, R) & ~free(gripper)',
                           				domain ='ball(obj) & Room(R) & gripper(gripper)'
                           				),
                           			Action('Drop(obj, R, gripper)',
                           				precond='carry(obj, gripper) & at_robby(R)',
                           				effect ='at(obj, R) & free(gripper) & ~carry(obj, gripper)',
                           				domain ='ball(obj) & Room(R) & gripper(gripper)'
                           				)],
                           domain='Room(A) & Room(B) & ball(W) & ball(X) & ball(Y) & ball(Z) & gripper(left) & gripper(right)')

shoppingProblem = gripper()
solution = GraphPlan(shoppingProblem).execute()
print(linearize(solution))
```
```
Traceback (most recent call last):
  File "/home/mat/Doctorado/PDDL-Dataset/aima-python/PLANIFICADOR.py", line 102, in <module>
    solution = GraphPlan(shoppingProblem).execute()
  File "/home/mat/Doctorado/PDDL-Dataset/aima-python/planning.py", line 1004, in execute
    solution = self.extract_solution(self.graph.planning_problem.goals, -1)
  File "/home/mat/Doctorado/PDDL-Dataset/aima-python/planning.py", line 948, in extract_solution
    actions.append(level.next_state_links[goal])
KeyError: at(W, B)
```
I was use python 3.5.9 and 3.6.9 and I get the same results.

I Hope you can help me

Regards.

**Comment by Chipe1** [comment]
The symbols are case sensitive. Lowercase are variables ; Uppercase are props. 
```
def Blockworld_test():
    return PlanningProblem( initial = 'HandEmpty & OnTable(A) & OnTable(B) & Clear(A) & Clear(B)',
                            goals =  'On(A, B)',
                            actions = [Action('Pick_Up(x)',
                                                precond='Clear(x) & OnTable(x) & HandEmpty',
                                                effect='~Clear(x) & ~OnTable(x) & ~HandEmpty & Holding(x)',
                                                domain='Block(x)'),
                                        Action('Put_Down(x)',
                                                precond='Holding(x)',
                                                effect='~Holding(x) & Clear(x) & HandEmpty & OnTable(x)',
                                                domain='Block(x)'),
                                        Action('Stack(x, y)',
                                                precond='Holding(x) & Clear(y)',
                                                effect='~Holding(x) & ~Clear(y) & Clear(x) & HandEmpty & On(x, y)',
                                                domain='Block(x) & Block(y)'),
                                        Action('Unstack(x, y)',
                                                precond='On(x,y) & Clear(x) & HandEmpty',
                                                effect='Holding(x) & Clear(y) & ~Clear(x) & ~HandEmpty & ~On(x, y)',
                                                domain='Block(x) & Block(y)')],
                            domain = 'Block(A) & Block(B)') 
```

**Comment by dmeoli** [comment]
The reported `KeyError` no longer reproduces on current master (the planning module was substantially reworked since). As @Chipe1 noted, the symbol convention is case-sensitive — capitalized names are propositions/constants, lowercase are variables. Both the original lowercase Blockworld and the capitalized version now solve, e.g. the capitalized form yields `[Pick_Up(A), Stack(A, B)]`. Closing as answered/resolved; please reopen with a current traceback if you still hit it.
