### ISSUE TITLE
No module named 'skbuild'

### ISSUE THREAD

**Issue by philiprbrenan** [aimacode/aima-python#1219]
I am trying to install aima-python.  As requested, I ran:

`pip install -r requirements.txt`

I get the following message:
`
    ModuleNotFoundError: No module named 'skbuild'`

Attempts to install skbuild get:

`404 Client Error: Not Found for url: https://pypi.org/simple/skbuild/`

Please tell me how to satisfy the requirement for **skbuild**?

Thanks!

```
pip3 -V
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)

phil@pousadouros:~/z/aima/aima-python$ pip3 install -r requirements.txt
Collecting cvxopt (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/bd/da/385b85d3ef47e72a242abe304a03cea098cb9ba6cdb795b044e8c7806b18/cvxopt-1.2.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting image (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/84/be/961693ed384aa91bcc07525c90e3a34bc06c75f131655dfe21310234c933/image-1.5.33.tar.gz
Collecting ipython (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/23/6a/210816c943c9aeeb29e4e18a298f14bf0e118fe222a23e13bfcc2d41b0a4/ipython-7.16.1-py3-none-any.whl
Collecting ipythonblocks (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/0a/2e/2ffc1f1f17fe48f98c9004b2612336384827b5c5889340027fd6046a7e7a/ipythonblocks-1.9.0-py2.py3-none-any.whl
Collecting ipywidgets (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/11/53/084940a83a8158364e630a664a30b03068c25ab75243224d6b488800d43a/ipywidgets-7.6.3-py2.py3-none-any.whl
Collecting jupyter (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/83/df/0f5dd132200728a86190397e1ea87cd76244e42d39ec5e88efd25b2abd7e/jupyter-1.0.0-py2.py3-none-any.whl
Collecting keras (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/44/e1/dc0757b20b56c980b5553c1b5c4c32d378c7055ab7bfa92006801ad359ab/Keras-2.4.3-py2.py3-none-any.whl
Collecting matplotlib (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/09/03/b7b30fa81cb687d1178e085d0f01111ceaea3bf81f9330c937fb6f6c8ca0/matplotlib-3.3.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting networkx (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/9b/cd/dc52755d30ba41c60243235460961fc28022e5b6731f16c268667625baea/networkx-2.5-py3-none-any.whl
Collecting numpy (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/45/b2/6c7545bb7a38754d63048c7696804a0d947328125d81bf12beaa692c3ae3/numpy-1.19.5-cp36-cp36m-manylinux1_x86_64.whl
Collecting opencv-python (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/bb/08/9dbc183a3ac6baa95fabf749ddb531bd26256edfff5b6c2195eca26258e9/opencv-python-4.5.1.48.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-vqcgeznw/opencv-python/setup.py", line 10, in <module>
        import skbuild
    ModuleNotFoundError: No module named 'skbuild'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vqcgeznw/opencv-python/
`
```

**Comment by huntleym** [comment]
You can try 'pip3 install --upgrade pip' and then check to see you have the latest version of pip afterwards with 'pip -V'

**Comment by dmeoli** [comment]
'No module named skbuild' is a local build-environment issue (a transitive dependency needs scikit-build / updated pip). Not a library bug. Closing — a clean virtualenv with current pip should resolve it.
