### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by taofuns** [aimacode/aima-python#1281]
how to solve this? There seem to be some errors when installing packages.
I use python3.11.5.
```
pip install -r requirements.txt 
Collecting cvxopt (from -r requirements.txt (line 1))
  Obtaining dependency information for cvxopt from https://files.pythonhosted.org/packages/44/b1/b27dcf10dc6b61ffeb84bcf684d83ca90557b717d80b78a4758576c17010/cvxopt-1.3.2-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached cvxopt-1.3.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (1.3 kB)
Collecting image (from -r requirements.txt (line 2))
  Using cached image-1.5.33.tar.gz (15 kB)
  Preparing metadata (setup.py) ... done
Collecting ipython (from -r requirements.txt (line 3))
  Obtaining dependency information for ipython from https://files.pythonhosted.org/packages/52/d1/f70cdafba20030cbc1412d7a7d6a89c5035071835cc50e47fc5ed8da553c/ipython-8.14.0-py3-none-any.whl.metadata
  Using cached ipython-8.14.0-py3-none-any.whl.metadata (5.8 kB)
Collecting ipythonblocks (from -r requirements.txt (line 4))
  Using cached ipythonblocks-1.9.0-py2.py3-none-any.whl (13 kB)
Collecting ipywidgets (from -r requirements.txt (line 5))
  Obtaining dependency information for ipywidgets from https://files.pythonhosted.org/packages/b8/d4/ce436660098b2f456e2b8fdf76d4f33cbc3766c874c4aa2f772c7a5e943f/ipywidgets-8.1.0-py3-none-any.whl.metadata
  Using cached ipywidgets-8.1.0-py3-none-any.whl.metadata (2.4 kB)
Collecting jupyter (from -r requirements.txt (line 6))
  Using cached jupyter-1.0.0-py2.py3-none-any.whl (2.7 kB)
Collecting keras (from -r requirements.txt (line 7))
  Obtaining dependency information for keras from https://files.pythonhosted.org/packages/2e/f3/19da7511b45e80216cbbd9467137b2d28919c58ba1ccb971435cb631e470/keras-2.13.1-py3-none-any.whl.metadata
  Using cached keras-2.13.1-py3-none-any.whl.metadata (2.4 kB)
Collecting matplotlib (from -r requirements.txt (line 8))
  Obtaining dependency information for matplotlib from https://files.pythonhosted.org/packages/8d/22/719f4fff33b13b0708711fb52ca3fc44617a26728e0e023358288d5197ae/matplotlib-3.7.2-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached matplotlib-3.7.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting networkx (from -r requirements.txt (line 9))
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting numpy (from -r requirements.txt (line 10))
  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/c3/ea/1d95b399078ecaa7b5d791e1fdbb3aee272077d9fd5fb499593c87dec5ea/numpy-1.25.2-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached numpy-1.25.2-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.6 kB)
Collecting opencv-python (from -r requirements.txt (line 11))
  Obtaining dependency information for opencv-python from https://files.pythonhosted.org/packages/32/a6/4321f0f30ee11d6d85f49251d417f4e885fe7638b5ac50b7e3c80cccf141/opencv_python-4.8.0.76-cp37-abi3-macosx_11_0_arm64.whl.metadata
  Using cached opencv_python-4.8.0.76-cp37-abi3-macosx_11_0_arm64.whl.metadata (19 kB)
Collecting pandas (from -r requirements.txt (line 12))
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/8d/08/1cf87814dcd87604807971abc743b12e635de36d820be7b50e2b6aa9e1b5/pandas-2.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached pandas-2.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (18 kB)
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (9.2.0)
Collecting pytest-cov (from -r requirements.txt (line 14))
  Obtaining dependency information for pytest-cov from https://files.pythonhosted.org/packages/a7/4b/8b78d126e275efa2379b1c2e09dc52cf70df16fc3b90613ef82531499d73/pytest_cov-4.1.0-py3-none-any.whl.metadata
  Using cached pytest_cov-4.1.0-py3-none-any.whl.metadata (26 kB)
Collecting qpsolvers (from -r requirements.txt (line 15))
  Obtaining dependency information for qpsolvers from https://files.pythonhosted.org/packages/e0/1b/5cf3888d13873a8d6e85fc3676c2e972e2a6a9fc059fecdaf12b02c9552f/qpsolvers-4.0.0-py3-none-any.whl.metadata
  Using cached qpsolvers-4.0.0-py3-none-any.whl.metadata (16 kB)
Collecting scipy (from -r requirements.txt (line 16))
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/63/b9/0344b60e7c577eb637785841222fde8ef7928ec4797be1a34ca39bfe31dc/scipy-1.11.2-cp310-cp310-macosx_12_0_arm64.whl.metadata
  Using cached scipy-1.11.2-cp310-cp310-macosx_12_0_arm64.whl.metadata (100 kB)
Collecting sortedcontainers (from -r requirements.txt (line 17))
  Using cached sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting tensorflow (from -r requirements.txt (line 18))
  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/4e/d0/167c25cf115d6604adf11bb075a689dcb35bc5e351501e7dfdedef294498/tensorflow-2.13.0-cp310-cp310-macosx_12_0_arm64.whl.metadata
  Using cached tensorflow-2.13.0-cp310-cp310-macosx_12_0_arm64.whl.metadata (2.6 kB)
Collecting django (from image->-r requirements.txt (line 2))
  Obtaining dependency information for django from https://files.pythonhosted.org/packages/7f/9e/fc6bab255ae10bc57fa2f65646eace3d5405fbb7f5678b90140052d1db0f/Django-4.2.4-py3-none-any.whl.metadata
  Using cached Django-4.2.4-py3-none-any.whl.metadata (4.1 kB)
Collecting six (from image->-r requirements.txt (line 2))
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting backcall (from ipython->-r requirements.txt (line 3))
  Using cached backcall-0.2.0-py2.py3-none-any.whl (11 kB)
Collecting decorator (from ipython->-r requirements.txt (line 3))
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Collecting jedi>=0.16 (from ipython->-r requirements.txt (line 3))
  Obtaining dependency information for jedi>=0.16 from https://files.pythonhosted.org/packages/8e/46/7e3ae3aa2dcfcffc5138c6cef5448523218658411c84a2000bf75c8d3ec1/jedi-0.19.0-py2.py3-none-any.whl.metadata
  Using cached jedi-0.19.0-py2.py3-none-any.whl.metadata (22 kB)
Collecting matplotlib-inline (from ipython->-r requirements.txt (line 3))
  Using cached matplotlib_inline-0.1.6-py3-none-any.whl (9.4 kB)
Collecting pickleshare (from ipython->-r requirements.txt (line 3))
  Using cached pickleshare-0.7.5-py2.py3-none-any.whl (6.9 kB)
Collecting prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 (from ipython->-r requirements.txt (line 3))
  Obtaining dependency information for prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 from https://files.pythonhosted.org/packages/a9/b4/ba77c84edf499877317225d7b7bc047a81f7c2eed9628eeb6bab0ac2e6c9/prompt_toolkit-3.0.39-py3-none-any.whl.metadata
  Using cached prompt_toolkit-3.0.39-py3-none-any.whl.metadata (6.4 kB)
Collecting pygments>=2.4.0 (from ipython->-r requirements.txt (line 3))
  Obtaining dependency information for pygments>=2.4.0 from https://files.pythonhosted.org/packages/43/88/29adf0b44ba6ac85045e63734ae0997d3c58d8b1a91c914d240828d0d73d/Pygments-2.16.1-py3-none-any.whl.metadata
  Using cached Pygments-2.16.1-py3-none-any.whl.metadata (2.5 kB)
Collecting stack-data (from ipython->-r requirements.txt (line 3))
  Using cached stack_data-0.6.2-py3-none-any.whl (24 kB)
Collecting traitlets>=5 (from ipython->-r requirements.txt (line 3))
  Using cached traitlets-5.9.0-py3-none-any.whl (117 kB)
Collecting pexpect>4.3 (from ipython->-r requirements.txt (line 3))
  Using cached pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
Collecting appnope (from ipython->-r requirements.txt (line 3))
  Using cached appnope-0.1.3-py2.py3-none-any.whl (4.4 kB)
Collecting notebook>=4.0 (from ipythonblocks->-r requirements.txt (line 4))
  Obtaining dependency information for notebook>=4.0 from https://files.pythonhosted.org/packages/79/97/b803f9686fe25b40c8eca2d1ba440b2f878f23b87765d18fe93dd323f0b7/notebook-7.0.3-py3-none-any.whl.metadata
  Using cached notebook-7.0.3-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests>=1.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from ipythonblocks->-r requirements.txt (line 4)) (2.23.0)
Collecting comm>=0.1.3 (from ipywidgets->-r requirements.txt (line 5))
  Obtaining dependency information for comm>=0.1.3 from https://files.pythonhosted.org/packages/fe/47/0133ac1b7dc476ed77710715e98077119b3d9bae56b13f6f9055e7da1c53/comm-0.1.4-py3-none-any.whl.metadata
  Using cached comm-0.1.4-py3-none-any.whl.metadata (4.2 kB)
Collecting widgetsnbextension~=4.0.7 (from ipywidgets->-r requirements.txt (line 5))
  Obtaining dependency information for widgetsnbextension~=4.0.7 from https://files.pythonhosted.org/packages/8e/d4/d31b12ac0b87e8cc9fdb6ea1eb6596de405eaaa2f25606aaa755d0eebbc0/widgetsnbextension-4.0.8-py3-none-any.whl.metadata
  Using cached widgetsnbextension-4.0.8-py3-none-any.whl.metadata (1.6 kB)
Collecting jupyterlab-widgets~=3.0.7 (from ipywidgets->-r requirements.txt (line 5))
  Obtaining dependency information for jupyterlab-widgets~=3.0.7 from https://files.pythonhosted.org/packages/74/5e/2475ac62faf2e342b2bf20b8d8e375f49400ecb38f52e4e0a7557eb1cedb/jupyterlab_widgets-3.0.8-py3-none-any.whl.metadata
  Using cached jupyterlab_widgets-3.0.8-py3-none-any.whl.metadata (4.1 kB)
Collecting qtconsole (from jupyter->-r requirements.txt (line 6))
  Using cached qtconsole-5.4.3-py3-none-any.whl (121 kB)
Collecting jupyter-console (from jupyter->-r requirements.txt (line 6))
  Using cached jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Collecting nbconvert (from jupyter->-r requirements.txt (line 6))
  Obtaining dependency information for nbconvert from https://files.pythonhosted.org/packages/a4/a6/072b6fd04616f1409f37ef5967ea5bbbeea1447d4494c2d98658a95fc985/nbconvert-7.8.0-py3-none-any.whl.metadata
  Using cached nbconvert-7.8.0-py3-none-any.whl.metadata (8.0 kB)
Collecting ipykernel (from jupyter->-r requirements.txt (line 6))
  Obtaining dependency information for ipykernel from https://files.pythonhosted.org/packages/ca/ca/1089ddd8dd3ba03ea593bf20cdc2f7fe02526dcd7d966b7da47aa105e65b/ipykernel-6.25.1-py3-none-any.whl.metadata
  Using cached ipykernel-6.25.1-py3-none-any.whl.metadata (6.3 kB)
Collecting contourpy>=1.0.1 (from matplotlib->-r requirements.txt (line 8))
  Obtaining dependency information for contourpy>=1.0.1 from https://files.pythonhosted.org/packages/15/c4/aae3954fce0e22362cc55430d1a395bf0be5a22b40fce63edda9eb6ea339/contourpy-1.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached contourpy-1.1.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (5.7 kB)
Collecting cycler>=0.10 (from matplotlib->-r requirements.txt (line 8))
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting fonttools>=4.22.0 (from matplotlib->-r requirements.txt (line 8))
  Obtaining dependency information for fonttools>=4.22.0 from https://files.pythonhosted.org/packages/21/66/bddd878452ae1e2d5f5891daa6bcce594d6b19396d33b8798e722837b222/fonttools-4.42.1-cp310-cp310-macosx_10_9_universal2.whl.metadata
  Using cached fonttools-4.42.1-cp310-cp310-macosx_10_9_universal2.whl.metadata (150 kB)
Collecting kiwisolver>=1.0.1 (from matplotlib->-r requirements.txt (line 8))
  Obtaining dependency information for kiwisolver>=1.0.1 from https://files.pythonhosted.org/packages/23/11/6fb190bae4b279d712a834e7b1da89f6dcff6791132f7399aa28a57c3565/kiwisolver-1.4.5-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached kiwisolver-1.4.5-cp310-cp310-macosx_11_0_arm64.whl.metadata (6.4 kB)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from matplotlib->-r requirements.txt (line 8)) (23.1)
Collecting pyparsing<3.1,>=2.3.1 (from matplotlib->-r requirements.txt (line 8))
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting python-dateutil>=2.7 (from matplotlib->-r requirements.txt (line 8))
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pytz>=2020.1 (from pandas->-r requirements.txt (line 12))
  Using cached pytz-2023.3-py2.py3-none-any.whl (502 kB)
Requirement already satisfied: tzdata>=2022.1 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pandas->-r requirements.txt (line 12)) (2022.7)
Requirement already satisfied: pytest>=4.6 in /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages (from pytest-cov->-r requirements.txt (line 14)) (7.4.0)
Collecting coverage[toml]>=5.2.1 (from pytest-cov->-r requirements.txt (line 14))
  Obtaining dependency information for coverage[toml]>=5.2.1 from https://files.pythonhosted.org/packages/9e/3b/5bdcbd8c64abf4eb1d61addf11754ad5883f3bda1d612cc843cbb3958902/coverage-7.3.0-cp310-cp310-macosx_11_0_arm64.whl.metadata
  Using cached coverage-7.3.0-cp310-cp310-macosx_11_0_arm64.whl.metadata (8.1 kB)
Collecting daqp>=0.5.1 (from qpsolvers->-r requirements.txt (line 15))
  Using cached daqp-0.5.1-cp310-cp310-macosx_11_0_arm64.whl (85 kB)
Collecting ecos>=2.0.8 (from qpsolvers->-r requirements.txt (line 15))
  Using cached ecos-2.0.12.tar.gz (142 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting osqp>=0.6.2 (from qpsolvers->-r requirements.txt (line 15))
  Using cached osqp-0.6.3.tar.gz (228 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [117 lines of output]
      Collecting oldest-supported-numpy
        Obtaining dependency information for oldest-supported-numpy from https://files.pythonhosted.org/packages/94/9a/756fef9346e5ca2289cb70d73990b4c9f25446a885c1186cfb93a85e7da0/oldest_supported_numpy-2023.8.3-py3-none-any.whl.metadata
        Using cached oldest_supported_numpy-2023.8.3-py3-none-any.whl.metadata (9.5 kB)
      Collecting setuptools>=40.8.0
        Obtaining dependency information for setuptools>=40.8.0 from https://files.pythonhosted.org/packages/4f/ab/0bcfebdfc3bfa8554b2b2c97a555569c4c1ebc74ea288741ea8326c51906/setuptools-68.1.2-py3-none-any.whl.metadata
        Using cached setuptools-68.1.2-py3-none-any.whl.metadata (6.2 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting setuptools_scm>=6.2
        Using cached setuptools_scm-7.1.0-py3-none-any.whl (43 kB)
      Collecting qdldl
        Using cached qdldl-0.1.7.post0.tar.gz (70 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting numpy==1.21.6 (from oldest-supported-numpy)
        Using cached numpy-1.21.6-cp310-cp310-macosx_11_0_arm64.whl (12.4 MB)
      Collecting packaging>=20.0 (from setuptools_scm>=6.2)
        Using cached packaging-23.1-py3-none-any.whl (48 kB)
      Collecting typing-extensions (from setuptools_scm>=6.2)
        Obtaining dependency information for typing-extensions from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
        Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
      Collecting tomli>=1.0.0 (from setuptools_scm>=6.2)
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Collecting scipy>=0.13.2 (from qdldl)
        Obtaining dependency information for scipy>=0.13.2 from https://files.pythonhosted.org/packages/63/b9/0344b60e7c577eb637785841222fde8ef7928ec4797be1a34ca39bfe31dc/scipy-1.11.2-cp310-cp310-macosx_12_0_arm64.whl.metadata
        Using cached scipy-1.11.2-cp310-cp310-macosx_12_0_arm64.whl.metadata (100 kB)
      Using cached oldest_supported_numpy-2023.8.3-py3-none-any.whl (4.8 kB)
      Using cached setuptools-68.1.2-py3-none-any.whl (805 kB)
      Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Using cached scipy-1.11.2-cp310-cp310-macosx_12_0_arm64.whl (29.6 MB)
      Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
      Building wheels for collected packages: qdldl
        Building wheel for qdldl (pyproject.toml): started
        Building wheel for qdldl (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
      
        × Building wheel for qdldl (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [65 lines of output]
            running bdist_wheel
            running build
            running build_ext
            Traceback (most recent call last):
              File "<string>", line 81, in build_extensions
              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 420, in check_output
                return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 501, in run
                with Popen(*popenargs, **kwargs) as process:
              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 969, in __init__
                self._execute_child(args, executable, preexec_fn, close_fds,
              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1845, in _execute_child
                raise child_exception_type(errno_num, err_msg, err_filename)
            FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
      
            During handling of the above exception, another exception occurred:
      
            Traceback (most recent call last):
              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
                main()
              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
                json_out['return_val'] = hook(**hook_input['kwargs'])
              File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
                return _build_backend().build_wheel(wheel_directory, config_settings,
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 434, in build_wheel
                return self._build_with_temp_dir(
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 419, in _build_with_temp_dir
                self.run_setup()
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 341, in run_setup
                exec(code, locals())
              File "<string>", line 113, in <module>
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
                return distutils.core.setup(**attrs)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
                return run_commands(dist)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
                dist.run_commands()
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
                self.run_command(cmd)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
                super().run_command(command)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/normal/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
                self.run_command("build")
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
                super().run_command(command)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
                self.run_command(cmd_name)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
                self.distribution.run_command(command)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1233, in run_command
                super().run_command(command)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
                cmd_obj.run()
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
                _build_ext.run(self)
              File "/private/var/folders/2l/tndyjrks6c5fjsrh37jcxhk80000gp/T/pip-build-env-79x47lgq/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
                self.build_extensions()
              File "<string>", line 83, in build_extensions
            RuntimeError: CMake must be installed to build qdldl
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for qdldl
      Failed to build qdldl
      ERROR: Could not build wheels for qdldl, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by wodin** [comment]
>             FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
[...]
>             RuntimeError: CMake must be installed to build qdldl

You will need to [install CMake](https://cmake.org/download/) and then try again

**Comment by taofuns** [comment]
> > ```
> >         FileNotFoundError: [Errno 2] No such file or directory: 'cmake'
> > ```
> 
> [...]
> 
> > ```
> >         RuntimeError: CMake must be installed to build qdldl
> > ```
> 
> You will need to [install CMake](https://cmake.org/download/) and then try again

Thanks, I had used `pip3 install cmake`, it didn’t work. Then I tried “brew install cmake”, the problem was solved.
